/**
 * エラーコード定数
 */

import type { ErrorCode } from '../../types';

export const ERROR_CODES = {
  // 一般的なエラー
  VALIDATION_ERROR: 'VALIDATION_ERROR' as ErrorCode,
  NOT_FOUND: 'NOT_FOUND' as ErrorCode,
  AUTHENTICATION_ERROR: 'AUTHENTICATION_ERROR' as ErrorCode,
  PROCESS_ERROR: 'PROCESS_ERROR' as ErrorCode,
  WEBSOCKET_ERROR: 'WEBSOCKET_ERROR' as ErrorCode,
  INTERNAL_ERROR: 'INTERNAL_ERROR' as ErrorCode,

  // Amazon Q関連エラー
  Q_COMMAND_ERROR: 'Q_COMMAND_ERROR' as ErrorCode,
  Q_ABORT_ERROR: 'Q_ABORT_ERROR' as ErrorCode,
  Q_HISTORY_ERROR: 'Q_HISTORY_ERROR' as ErrorCode,
  Q_HISTORY_UNAVAILABLE: 'Q_HISTORY_UNAVAILABLE' as ErrorCode,
  Q_HISTORY_DETAILED_ERROR: 'Q_HISTORY_DETAILED_ERROR' as ErrorCode,
  Q_PROJECTS_ERROR: 'Q_PROJECTS_ERROR' as ErrorCode,
  Q_PROJECTS_UNAVAILABLE: 'Q_PROJECTS_UNAVAILABLE' as ErrorCode,
  Q_RESUME_ERROR: 'Q_RESUME_ERROR' as ErrorCode,
  Q_RESUME_UNAVAILABLE: 'Q_RESUME_UNAVAILABLE' as ErrorCode,
  Q_RESUME_NO_HISTORY: 'Q_RESUME_NO_HISTORY' as ErrorCode,
  Q_PROJECT_START_ERROR: 'Q_PROJECT_START_ERROR' as ErrorCode,
  Q_CLI_NOT_AVAILABLE: 'Q_CLI_NOT_AVAILABLE' as ErrorCode,
  Q_CLI_NOT_FOUND: 'Q_CLI_NOT_FOUND' as ErrorCode,
  Q_CLI_PERMISSION_ERROR: 'Q_CLI_PERMISSION_ERROR' as ErrorCode,

  // ソケット関連エラー
  SOCKET_ERROR: 'SOCKET_ERROR' as ErrorCode,
} as const;

// HTTP ステータスコードのマッピング
export const ERROR_STATUS_CODES = {
  [ERROR_CODES.VALIDATION_ERROR]: 400,
  [ERROR_CODES.NOT_FOUND]: 404,
  [ERROR_CODES.AUTHENTICATION_ERROR]: 401,
  [ERROR_CODES.PROCESS_ERROR]: 500,
  [ERROR_CODES.WEBSOCKET_ERROR]: 500,
  [ERROR_CODES.INTERNAL_ERROR]: 500,
  [ERROR_CODES.Q_COMMAND_ERROR]: 500,
  [ERROR_CODES.Q_ABORT_ERROR]: 500,
  [ERROR_CODES.Q_HISTORY_ERROR]: 500,
  [ERROR_CODES.Q_HISTORY_UNAVAILABLE]: 503,
  [ERROR_CODES.Q_HISTORY_DETAILED_ERROR]: 500,
  [ERROR_CODES.Q_PROJECTS_ERROR]: 500,
  [ERROR_CODES.Q_PROJECTS_UNAVAILABLE]: 503,
  [ERROR_CODES.Q_RESUME_ERROR]: 500,
  [ERROR_CODES.Q_RESUME_UNAVAILABLE]: 503,
  [ERROR_CODES.Q_RESUME_NO_HISTORY]: 404,
  [ERROR_CODES.Q_PROJECT_START_ERROR]: 500,
  [ERROR_CODES.Q_CLI_NOT_AVAILABLE]: 503,
  [ERROR_CODES.Q_CLI_NOT_FOUND]: 404,
  [ERROR_CODES.Q_CLI_PERMISSION_ERROR]: 403,
  [ERROR_CODES.SOCKET_ERROR]: 500,
} as const;
