name: Build and Test

on:
  push:
    branches: [main, feat/*, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build shared package
        run: pnpm --filter @quincy/shared build

      - name: Build backend
        run: pnpm --filter backend build

      - name: Build frontend
        run: pnpm --filter frontend build

      - name: Build docs
        run: pnpm --filter docs build

      - name: Check build artifacts
        run: |
          echo "Checking build outputs..."
          ls -la packages/shared/dist/
          ls -la apps/backend/dist/
          ls -la apps/frontend/dist/
          ls -la apps/docs/.vitepress/dist/

      - name: Run backend tests
        run: pnpm --filter backend test
        timeout-minutes: 5
        env:
          NODE_ENV: test

      - name: Run frontend tests
        run: pnpm --filter frontend test:ci
        timeout-minutes: 5
        env:
          NODE_ENV: test
          CI: true
