name: Build Check

on:
  push:
    branches: [ main, feat/*, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 10

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install

    - name: Build shared package
      run: pnpm --filter @quincy/shared build

    - name: Build backend
      run: pnpm --filter backend build

    - name: Build frontend
      run: pnpm --filter frontend build

    - name: Check build artifacts
      run: |
        echo "Checking build outputs..."
        ls -la packages/shared/dist/
        ls -la apps/backend/dist/
        ls -la apps/frontend/dist/